apiVersion: v1
kind: Secret
metadata:
  name: elastic-admin-auth
type: kubernetes.io/basic-auth
data:
  username: username
  password: password
  roles: superuser
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.17.3
  auth:
    fileRealm:
    - secretName: elastic-admin-auth
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        storageClassName: openebs-local
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1G
