apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elastic
resources:
  - elastic.yaml
patchesStrategicMerge:
  - patch.yaml
secretGenerator:
  - name: elastic-admin-auth
    type: kubernetes.io/basic-auth
    behavior: merge
    env: .env
generatorOptions:
  disableNameSuffixHash: true
