alloy:
  enabled: false

engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false

loki:
  enabled: false

openebs-crds:
  csi:
    volumeSnapshots:
      enabled: false
