apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters: # []CiliumBGPVirtualRouter
  - localASN: 65000
    exportPodCIDR: true
    neighbors: # []CiliumBGPNeighbor
    - peerAddress: 192.168.0.2/32
      peerASN: 65000
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
