apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opencloud
resources:
  - opencloud.yaml
patchesStrategicMerge:
  - patch.yaml
secretGenerator:
  - name: opencloud-secret
    behavior: merge
    env: .env
generatorOptions:
  disableNameSuffixHash: true
