global:
  enabled: true
  tlsDisable: false

injector:
  enabled: false

server:
  enabled: true
  nodeSelector:
    kubernetes.io/hostname: node-name
  volumes:
    - name: vault-server-tls
      secret:
        defaultMode: 420
        secretName: vault-tls
  volumeMounts:
    - mountPath: /vault/userconfig/vault-server-tls
      name: vault-server-tls
      readOnly: true
  dataStorage:
    enabled: true
    storageClass: openebs-local
  standalone:
    enabled: true
    config: |
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        proxy_protocol_behavior = "use_always"
        tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
        tls_key_file = "/vault/userconfig/vault-server-tls/tls.key"
        tls_disable_client_certs = "true"
      }
      storage "file" {
        path = "/vault/data"
      }
  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
      - hosts:
          - vault.domain.com
        secretName: vault-tls

ui:
  enabled: true
