apiVersion: v1
kind: Service
metadata:
  name: network-multitool
  labels:
    app.kubernetes.io/name: network-multitool
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: network-multitool
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-multitool
  labels:
    app.kubernetes.io/name: network-multitool
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: network-multitool
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: network-multitool
    spec:
      containers:
        - name: network-multitool
          image: wbitt/network-multitool:extra
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          resources: {}