apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openldap
resources:
  - openldap.yaml
patchesStrategicMerge:
  - patch.yaml
secretGenerator:
  - name: openldap-secret
    behavior: merge
    env: .env
generatorOptions:
  disableNameSuffixHash: true