apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
  labels:
    app.kubernetes.io/name: openldap
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-secret
  labels:
    app.kubernetes.io/name: openldap
type: Opaque
data:
  LDAP_ROOT: dc=domain,dc=com
  LDAP_ADMIN_USERNAME: username
  LDAP_ADMIN_PASSWORD: password
  LDAP_CONFIG_ADMIN_ENABLED: yes
  LDAP_CONFIG_ADMIN_USERNAME: username
  LDAP_CONFIG_ADMIN_PASSWORD: password
  LDAP_PASSWORD_HASH: "{hash}"
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openldap
  ports:
    - name: ldap
      appProtocol: ldap
      port: 389
      protocol: TCP
      targetPort: ldap
    - name: ldaps
      appProtocol: ldaps
      port: 636
      protocol: TCP
      targetPort: ldaps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
  annotations:
    secret.reloader.stakater.com/reload: "openldap-tls"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: bitnami/openldap:2.5.16
          imagePullPolicy: Always
          env:
            - name: LDAP_ADD_SCHEMAS
              value: "yes"
            - name: LDAP_EXTRA_SCHEMAS
              value: "cosine,dyngroup,inetorgperson,nis"
            - name: LDAP_ALLOW_ANON_BINDING
              value: "no"
            - name: LDAP_CONFIGURE_PPOLICY
              value: "yes"
            - name: LDAP_PPOLICY_HASH_CLEARTEXT
              value: "yes"
            - name: LDAP_ENABLE_TLS
              value: "yes"
            - name: LDAP_TLS_CERT_FILE
              value: "/opt/bitnami/openldap/certs/tls.crt"
            - name: LDAP_TLS_KEY_FILE
              value: "/opt/bitnami/openldap/certs/tls.key"
            - name: LDAP_TLS_CA_FILE
              value: "/opt/bitnami/openldap/certs/ca.crt"
          envFrom:
            - secretRef:
                name: openldap-secret
          ports:
            - name: ldap
              containerPort: 1389
            - name: ldaps
              containerPort: 1636
          volumeMounts:
            - name: tls
              mountPath: /opt/bitnami/openldap/certs
              readOnly: true
            - name: data
              mountPath: /bitnami/openldap
          resources: {}
      volumes:
        - name: tls
          projected:
            sources:
            - secret:
                name: openldap-tls
            - secret:
                name: private-ca
        - name: data
          persistentVolumeClaim:
            claimName: openldap-pvc
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap-tls
  labels:
    app.kubernetes.io/name: openldap
spec:
  secretName: openldap-tls
  dnsNames:
    - openldap.domain.com
  issuerRef:
    name: issuer
    kind: ClusterIssuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: private-ca
        key: pkcs12-password
      profile: Modern2023