apiVersion: v1
kind: Namespace
metadata:
  name: org
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: org
spec:
  type: ExternalName
  externalName: openldap.openldap.svc.cluster.local
