controller:
  ingress:
    enabled: true
    hostName: jenkins.domain.com
    tls:
    - hosts:
        - jenkins.domain.com
      secretName: jenkins-tls
  initContainerEnv:
    - name: JAVA_OPTS
      value: "-Dhttps.proxyHost=192.168.0.1 -Dhttps.proxyPort=3128"
  javaOpts: >-
    -Dhttp.proxyHost=192.168.0.1
    -Dhttp.proxyPort=3128
    -Dhttps.proxyHost=192.168.0.1
    -Dhttps.proxyPort=3128