apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitea.yaml
  - gitea-configs.yaml
patchesStrategicMerge:
  - patch.yaml
secretGenerator:
  - name: gitea-secret
    namespace: gitea
    behavior: merge
    env: .env
generatorOptions:
  disableNameSuffixHash: true