apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
resources:
  - gitea.yaml
  - gitea-config.yaml
patchesStrategicMerge:
  - patch.yaml
secretGenerator:
  - name: gitea-secret
    behavior: merge
    env: .env
generatorOptions:
  disableNameSuffixHash: true
