apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak
data:
  theme.properties: |-
    import=common/keycloak
    locales=en
    welcomeRedirectUrl=${env.WELCOME_REDIRECT}
  index.ftl: |-
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta http-equiv="refresh" content="0; url=${properties.welcomeRedirectUrl}" />
        <meta name="robots" content="noindex, nofollow" />
        <script type="text/javascript">
          window.location.href = '${properties.welcomeRedirectUrl}'
        </script>
      </head>
      <body>
        If login page not shown, follow this <a href="${properties.welcomeRedirectUrl}">link</a>.
      </body>
    </html>
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak
type: Opaque
data:
  KEYCLOAK_ADMIN: username
  KEYCLOAK_ADMIN_PASSWORD: password
  KC_HOSTNAME: keycloak.domain.com
  KC_DB: db_type
  KC_DB_URL_HOST: db_host
  KC_DB_URL_DATABASE: db_name
  KC_DB_URL_PORT: port
  KC_DB_USERNAME: username
  KC_DB_PASSWORD: password
  WELCOME_REDIRECT: https://keycloak.domain.com/realms/org/account/#/personal-info
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
    app.kubernetes.io/instance: keycloak
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-discovery
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: keycloak
    app.kubernetes.io/instance: keycloak
  ports:
  - port: 7800
    protocol: TCP
    targetPort: 7800
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak
  annotations:
    secret.reloader.stakater.com/reload: "keycloak-tls"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      app.kubernetes.io/instance: keycloak
  serviceName: ""
  template:
    metadata:
      labels:
        app: keycloak
        app.kubernetes.io/instance: keycloak
    spec:
      containers:
      - name: keycloak
        args:
        - -Djgroups.dns.query=keycloak-discovery.keycloak
        - --verbose
        - start
        env:
        - name: KC_FEATURES
          value: declarative-user-profile
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KC_HTTPS_PORT
          value: "8443"
        - name: KC_HTTPS_CERTIFICATE_FILE
          value: /mnt/certificates/tls.crt
        - name: KC_HTTPS_CERTIFICATE_KEY_FILE
          value: /mnt/certificates/tls.key
        - name: KC_SPI_TRUSTSTORE_FILE_FILE
          value: /mnt/certificates/ca.p12
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_CACHE
          value: ispn
        - name: KC_CACHE_STACK
          value: kubernetes
        - name: KC_PROXY
          value: passthrough
        - name: KC_SPI_THEME_WELCOME_THEME
          value: welcome_redirect
        - name: KC_SPI_TRUSTSTORE_FILE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: pkcs12-password
              name: private-ca
        envFrom:
        - secretRef:
            name: keycloak-secret
        image: quay.io/keycloak/keycloak:23.0.7
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8443
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8443
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        startupProbe:
          failureThreshold: 600
          httpGet:
            path: /health/started
            port: 8443
            scheme: HTTPS
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        volumeMounts:
        - mountPath: /mnt/certificates
          name: keycloak-tls-certificates
        - mountPath: /opt/keycloak/themes/welcome_redirect/welcome
          name: theme
      restartPolicy: Always
      volumes:
      - name: keycloak-tls-certificates
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: keycloak-tls
          - secret:
              name: private-ca
      - name: theme
        configMap:
          name: keycloak-config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak
  annotations:
    cert-manager.io/cluster-issuer: "issuer"
    haproxy.org/ssl-passthrough: "true"
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - keycloak.domain.com
      secretName: keycloak-tls
  rules:
  - host: keycloak.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8443