apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: speedtest
  destination:
    server: https://kubernetes.default.svc
    namespace: <ns>
  source:
    repoURL: <https://repo.url>
    path: speedtest
    targetRevision: HEAD
  sources:
    - repoURL: <https://repo.url>
      path: speedtest
      targetRevision: HEAD
    - repoURL: <https://repo.url>
      path: speedtest
      targetRevision: HEAD
      kustomize:
        namespace: <ns>
        patches:
          - patch: |-
              $patch: delete
              apiVersion: v1
              kind: Secret
              metadata:
                name: speedtest-secret
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: speedtest
              spec:
                template:
                  spec:
                    containers:
                      - name: speedtest
                        image: <image-name>
                    nodeSelector:
                      kubernetes.io/hostname: <node-name>
          - patch: |-
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: speedtest-ingress
                annotations:
                  cert-manager.io/cluster-issuer: <issuer-name>
          - patch: |-
              - op: replace
                path: /spec/tls/0/hosts/0
                value: <speedtest.domain.com>
              - op: replace
                path: /spec/rules/0/host
                value: <speedtest.domain.com>
            target:
              kind: Ingress
              name: speedtest-ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
