apiVersion: v1
kind: Secret
metadata:
  name: speedtest-secret
  labels:
    app.kubernetes.io/name: speedtest
  annotations:
    avp.kubernetes.io/path: "secret/data/system/speedtest"
type: Opaque
data:
  PASSWORD: <password | base64encode>
  EMAIL: <email | base64encode>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-pvc
  labels:
    app.kubernetes.io/name: speedtest
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  labels:
    app.kubernetes.io/name: speedtest
spec:
  type: ClusterIP
  selector: 
    app.kubernetes.io/name: speedtest
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  labels:
    app.kubernetes.io/name: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: speedtest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: speedtest
    spec:
      containers:
        - name: speedtest
          image: ghcr.io/librespeed/speedtest:latest
          imagePullPolicy: Always
          env:
            - name: MODE
              value: "standalone"
            - name: TITLE
              value: "SpeedTest"
            - name: TELEMETRY
              value: "true"
            - name: ENABLE_ID_OBFUSCATION
              value: "true"
            - name: REDACT_IP_ADDRESSES
              value: "false"
            - name: DISABLE_IPINFO
              value: "true"
          envFrom:
            - secretRef:
                name: speedtest-secret
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /database
          resources: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: speedtest-pvc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest-ingress
  labels:
    app.kubernetes.io/name: speedtest
  annotations:
    cert-manager.io/cluster-issuer: "org-ca-issuer"
    cert-manager.io/common-name: "Speed Test"
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - speedtest.domain.com
      secretName: speedtest-tls
  rules:
  - host: speedtest.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: speedtest
            port:
              name: http