apiVersion: v1
kind: ConfigMap
metadata:
  name: speedtest-config
  labels:
    app.kubernetes.io/name: speedtest
data:  
  servers: |
    [
      {
        "name": "Server 1",
        "server": "https://server-1.speedtest.domain.com/",
        "dlURL": "garbage.php",
        "ulURL": "empty.php",
        "pingURL": "empty.php",
        "getIpURL": "getIP.php"
      }
    ]
---
apiVersion: v1
kind: Secret
metadata:
  name: speedtest-secret
  labels:
    app.kubernetes.io/name: speedtest
  annotations:
    avp.kubernetes.io/path: "secret/data/system/speedtest"
type: Opaque
data:
  PASSWORD: <password | base64encode>
  EMAIL: <email | base64encode>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-pvc
  labels:
    app.kubernetes.io/name: speedtest
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  labels:
    app.kubernetes.io/name: speedtest
spec:
  type: ClusterIP
  selector: 
    app.kubernetes.io/name: speedtest
  ports:
    - name: frontend
      port: 8080
      targetPort: frontend
    - name: backend
      port: 80
      targetPort: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  labels:
    app: speedtest
    app.kubernetes.io/name: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
      app.kubernetes.io/name: speedtest
  template:
    metadata:
      labels:
        app: speedtest
        app.kubernetes.io/name: speedtest
    spec:
      containers:
        - name: speedtest
          image: ghcr.io/librespeed/speedtest:5.4.1
          env:
            - name: MODE
              value: "frontend"
            - name: TITLE
              value: "SpeedTest"
            - name: TELEMETRY
              value: "true"
            - name: ENABLE_ID_OBFUSCATION
              value: "true"
            - name: REDACT_IP_ADDRESSES
              value: "false"
            - name: DISABLE_IPINFO
              value: "true"
            - name: WEBPORT
              value: "8080"
          envFrom:
            - secretRef:
                name: speedtest-secret
          ports:
            - name: frontend
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /database
            - name: config
              mountPath: /servers.json
              subPath: servers
          resources: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: speedtest-pvc
        - name: config
          configMap:
            name: speedtest-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-backend
  labels:
    app: speedtest-backend
    app.kubernetes.io/name: speedtest
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: speedtest-backend
      app.kubernetes.io/name: speedtest
  template:
    metadata:
      labels:
        app: speedtest-backend
        app.kubernetes.io/name: speedtest
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - lb-node-01
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: speedtest-backend
              topologyKey: kubernetes.io/hostname
      containers:
        - name: speedtest-backend
          image: ghcr.io/librespeed/speedtest:5.4.1
          env:
            - name: MODE
              value: "backend"
          ports:
            - name: backend
              containerPort: 80
          resources: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest-ingress
  labels:
    app.kubernetes.io/name: speedtest
  annotations:
    cert-manager.io/cluster-issuer: "issuer"
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - speedtest.domain.com
        - "*.speedtest.domain.com"
      secretName: speedtest-tls
  rules:
    - host: speedtest.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: speedtest
                port:
                  name: frontend
    - host: server-1.speedtest.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: speedtest
                port:
                  name: backend
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: speedtest-policy
spec:
  podSelector:
    matchLabels:
      app: speedtest-backend
  policyTypes:
    - Ingress
