apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nextcloud
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  source:
    repoURL: <https://repo.url>
    path: nextcloud
    targetRevision: HEAD
  sources:
    - repoURL: <https://repo.url>
      path: nextcloud
      targetRevision: HEAD
    - repoURL: <https://repo.url>
      path: nextcloud
      targetRevision: HEAD
      kustomize:
        namespace: nextcloud
        patches:
          - patch: |-
              $patch: delete
              apiVersion: v1
              kind: Secret
              metadata:
                name: nextcloud-secret
          - patch: |-
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: nextcloud-config
              data:
                remoteip.conf: |-
                  RemoteIPHeader <X-Forwarded-For>
                  RemoteIPInternalProxy <10.0.0.0/8>
                  RemoteIPInternalProxy <192.168.0.0/16>
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: nextcloud
              spec:
                template:
                  spec:
                    initContainers:
                      - name: init
                        image: <registry.private/nextcloud/nextcloud:30.0.5-apache>
                    containers:
                      - name: nextcloud
                        image: <registry.private/nextcloud/nextcloud:30.0.5-apache>
                        env:
                          - name: NEXTCLOUD_TRUSTED_DOMAINS
                            value: <"nextcloud.domain.com">
                          - name: TRUSTED_PROXIES
                            value: <"10.0.0.0/8 192.168.0.0/16">
                      - name: nextcloud-cron
                        image: <registry.private/nextcloud/nextcloud:30.0.5-apache>
                        env:
                          - name: NEXTCLOUD_TRUSTED_DOMAINS
                            value: <"nextcloud.domain.com">
                          - name: TRUSTED_PROXIES
                            value: <"10.0.0.0/8 192.168.0.0/16">
                    nodeSelector:
                      kubernetes.io/hostname: <node-name>
          - patch: |-
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: nextcloud-ingress
                annotations:
                  cert-manager.io/cluster-issuer: <issuer-name>
          - patch: |-
              - op: replace
                path: /spec/tls/0/hosts/0
                value: <nextcloud.domain.com>
              - op: replace
                path: /spec/rules/0/host
                value: <nextcloud.domain.com>
            target:
              kind: Ingress
              name: nextcloud-ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
