apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-aio-apache-pvc
  labels:
    app.kubernetes.io/name: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-aio-nextcloud-pvc
  labels:
    app.kubernetes.io/name: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-aio-nextcloud-data-pvc
  labels:
    app.kubernetes.io/name: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-aio-nextcloud-trusted-cacerts-pvc
  labels:
    app.kubernetes.io/name: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nextcloud-aio-apache
  name: nextcloud-aio-apache
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: 8000-udp
      port: 8000
      protocol: UDP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: nextcloud-aio-apache
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nextcloud-aio-imaginary
  name: nextcloud-aio-imaginary
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app.kubernetes.io/name: nextcloud-aio-imaginary
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nextcloud-aio-nextcloud
  name: nextcloud-aio-nextcloud
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    app.kubernetes.io/name: nextcloud-aio-nextcloud
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nextcloud-aio-notify-push
  name: nextcloud-aio-notify-push
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "7867"
      port: 7867
      targetPort: 7867
  selector:
    app.kubernetes.io/name: nextcloud-aio-notify-push
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    cert-manager.io/cluster-issuer: "org-ca-issuer"
    cert-manager.io/common-name: "Nextcloud"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "512k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-prefer-server-ciphers: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
      ssl_session_timeout 1d;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nextcloud.domain.com
      secretName: nextcloud-tls
  rules:
  - host: nextcloud.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-aio-apache
            port:
              number: 8000