apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  labels:
    app.kubernetes.io/name: nextcloud
data:
  NC_DOMAIN: nextcloud.domain.com
  OVERWRITEHOST: nextcloud.domain.com
  TEMP_APPSTORE: http://url/to/temp/appstore
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  labels:
    app.kubernetes.io/name: nextcloud
  annotations:
    avp.kubernetes.io/path: "secret/data/system/nextcloud"
type: Opaque
data:
  POSTGRES_HOST: <postgres_host | base64encode>
  POSTGRES_DB: <postgres_db | base64encode>
  POSTGRES_USER: <postgres_user | base64encode>
  POSTGRES_PASSWORD: <postgres_password | base64encode>
  REDIS_HOST: <redis_host | base64encode>
  REDIS_HOST_PASSWORD: <redis_host_password | base64encode>
  ADMIN_USER: <admin_user | base64encode>
  ADMIN_PASSWORD: <admin_password | base64encode>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  labels:
    app.kubernetes.io/name: nextcloud
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nextcloud-aio-apache
  name: nextcloud-aio-apache
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "11000"
      port: 11000
      targetPort: 11000
    - name: 11000-udp
      port: 11000
      protocol: UDP
      targetPort: 11000
  selector:
    app.kubernetes.io/name: nextcloud-aio-apache
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nextcloud-aio-imaginary
  name: nextcloud-aio-imaginary
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    app.kubernetes.io/name: nextcloud-aio-imaginary
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nextcloud-aio-nextcloud
  name: nextcloud-aio-nextcloud
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    app.kubernetes.io/name: nextcloud-aio-nextcloud
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    cert-manager.io/cluster-issuer: "org-ca-issuer"
    cert-manager.io/common-name: "Nextcloud"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "512k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-prefer-server-ciphers: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
      ssl_session_timeout 1d;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nextcloud.domain.com
      secretName: nextcloud-tls
  rules:
  - host: nextcloud.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-aio-apache
            port:
              number: 11000