apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  labels:
    app.kubernetes.io/name: nextcloud
data:
  NC_DOMAIN: nextcloud.domain.com
  OVERWRITEHOST: nextcloud.domain.com
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  labels:
    app.kubernetes.io/name: nextcloud
  annotations:
    avp.kubernetes.io/path: "secret/data/system/nextcloud"
type: Opaque
data:
  POSTGRES_HOST: <postgres_host | base64encode>
  POSTGRES_DB: <postgres_db | base64encode>
  POSTGRES_USER: <postgres_user | base64encode>
  POSTGRES_PASSWORD: <postgres_password | base64encode>
  REDIS_HOST: <redis_host | base64encode>
  REDIS_HOST_PASSWORD: <redis_host_password | base64encode>
  ADMIN_USER: <admin_user | base64encode>
  ADMIN_PASSWORD: <admin_password | base64encode>