apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: haproxy
spec:
  controller: haproxy.org/ingress-controller/haproxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress-config
  namespace: haproxy
data:
  ssl-redirect-port: "443"
