apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme.domain.com/directory
    email: user@domain.com
    caBundle: (cat ca.crt | base64 -w0)
    privateKeySecretRef:
      name: acme-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: haproxy