apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: cert-manager
data:
  tls.crt: (cat ca.crt | base64 -w0)
  tls.key: (cat ca.key | base64 -w0)
# if key is encrypted then decrypt first
# openssl rsa -in <encrypted_private.key> -out <decrypted_private.key>
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: ca-key-pair