gitea:
  additionalConfigFromEnvs:
    - name: GITEA__DATABASE__USER
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: user
    - name: GITEA__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: password
  additionalConfigSources:
    - secret:
        secretName: gitea-extra-secret
    - configMap:
        name: gitea-extra-config
  admin:
    existingSecret: gitea-admin-secret
  config:
    APP_NAME: "Gitea App"
    cache:
      ADAPTER: redis
      ENABLED: true
      HOST: "redis://:password@redis.domain.com:6379/0?pool_size=100&idle_timeout=180s&"
    database:
      DB_TYPE: postgres
      HOST: db.domain.com:5432
      NAME: db_name
    queue:
      TYPE: redis
      CONN_STR: "redis://:password@redis.domain.com:6379/0?pool_size=100&idle_timeout=180s&"
    session:
      PROVIDER: redis
      PROVIDER_CONFIG: "redis://:password@redis.domain.com:6379/0?pool_size=100&idle_timeout=180s&"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
  hosts:
    - host: gitea.domain.com
  tls:
    - hosts:
        - gitea.domain.com
      secretName: gitea-tls

nodeSelector:
  kubernetes.io/hostname: node-name

persistence:
  enabled: true
  storageClass: openebs-local
  claimName: gitea-pvc

postgresql:
  enabled: false

postgresql-ha:
  enabled: false

redis-cluster:
  enabled: false

service:
  ssh:
    type: NodePort
    nodePort: 32000
    externalTrafficPolicy: Local
