apiVersion: v1
kind: Service
metadata:
  name: harbor
spec:
  type: ExternalName
  externalName: 192.168.0.1
  ports:
  - name: https
    port: 38443
    protocol: TCP
    targetPort: 38443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harbor-ingress
  annotations:
    haproxy.org/ssl-passthrough: "true"
spec:
  ingressClassName: haproxy
  rules:
  - host: harbor.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harbor
            port:
              name: https