---
# Source: nextcloud-aio-helm-chart/templates/nextcloud-aio-namespace-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
# Source: nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-data-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nextcloud-aio-nextcloud-data
  name: nextcloud-aio-nextcloud-data
  namespace: nextcloud
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nextcloud-aio-nextcloud
  name: nextcloud-aio-nextcloud
  namespace: nextcloud
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# Source: nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-trusted-cacerts-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nextcloud-aio-nextcloud-trusted-cacerts
  name: nextcloud-aio-nextcloud-trusted-cacerts
  namespace: nextcloud
spec:
  storageClassName: openebs-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Source: nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace nextcloud
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: nextcloud-aio-imaginary
  name: nextcloud-aio-imaginary
  namespace: nextcloud
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: nextcloud-aio-imaginary
---
# Source: nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace nextcloud
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: nextcloud-aio-nextcloud
  name: nextcloud-aio-nextcloud
  namespace: nextcloud
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    io.kompose.service: nextcloud-aio-nextcloud
---
# Source: nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace nextcloud
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: nextcloud-aio-notify-push
  name: nextcloud-aio-notify-push
  namespace: nextcloud
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "7867"
      port: 7867
      targetPort: 7867
  selector:
    io.kompose.service: nextcloud-aio-notify-push
---
# Source: nextcloud-aio-helm-chart/templates/nextcloud-aio-imaginary-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace nextcloud
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: nextcloud-aio-imaginary
  name: nextcloud-aio-imaginary
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-imaginary
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace nextcloud
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-imaginary
    spec:
      containers:
        - env:
            - name: TZ
              value: "Asia/Jakarta"
          image: nextcloud/aio-imaginary:20231130_081302-latest
          name: nextcloud-aio-imaginary
          ports:
            - containerPort: 9000
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_NICE
          resources: {}
---
# Source: nextcloud-aio-helm-chart/templates/nextcloud-aio-nextcloud-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace nextcloud
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: nextcloud-aio-nextcloud
  name: nextcloud-aio-nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-nextcloud
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace nextcloud
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-nextcloud
    spec:
      initContainers:
        - name: delete
          image: alpine:3.18.5
          command:
            - rm
            - "-rf"
            - /nextcloud-aio-nextcloud/lost+found
          volumeMounts:
            - name: nextcloud-aio-nextcloud-trusted-cacerts
              mountPath: /nextcloud-aio-nextcloud-trusted-cacerts
            - name: nextcloud-aio-nextcloud
              mountPath: /nextcloud-aio-nextcloud
        - name: init-volumes
          image: alpine:3.18.5
          command:
            - chmod
            - "777"
            - /nextcloud-aio-nextcloud
            - /nextcloud-aio-nextcloud-trusted-cacerts
          volumeMounts:
            - name: nextcloud-aio-nextcloud-trusted-cacerts
              mountPath: /nextcloud-aio-nextcloud-trusted-cacerts
            - name: nextcloud-aio-nextcloud
              mountPath: /nextcloud-aio-nextcloud
      containers:
        - env:
            - name: SMTP_HOST
              value: ""
            - name: SMTP_SECURE
              value: ""
            - name: SMTP_PORT
              value: ""
            - name: SMTP_AUTHTYPE
              value: ""
            - name: SMTP_NAME
              value: ""
            - name: SMTP_PASSWORD
              value: ""
            - name: MAIL_FROM_ADDRESS
              value: ""
            - name: MAIL_DOMAIN
              value: ""
            - name: SUBSCRIPTION_KEY
              value: ""
            - name: APPS_ALLOWLIST
              value: ""
            - name: ADDITIONAL_TRUSTED_PROXY
              value: ""
            - name: ADDITIONAL_APKS
              value: "imagemagick"
            - name: ADDITIONAL_PHP_EXTENSIONS
              value: "imagick"
            - name: ADMIN_PASSWORD
              value: "admin_pass"
            - name: ADMIN_USER
              value: admin
            - name: APACHE_PORT
              value: "8000"
            - name: CLAMAV_ENABLED
              value: "no"
            - name: CLAMAV_HOST
              value: nextcloud-aio-clamav
            - name: COLLABORA_ENABLED
              value: "no"
            - name: COLLABORA_HOST
              value: nextcloud-aio-collabora
            - name: FULLTEXTSEARCH_ENABLED
              value: "no"
            - name: FULLTEXTSEARCH_HOST
              value: nextcloud-aio-fulltextsearch
            - name: FULLTEXTSEARCH_PASSWORD
              value: ""
            - name: IMAGINARY_ENABLED
              value: "yes"
            - name: IMAGINARY_HOST
              value: nextcloud-aio-imaginary
            - name: INSTALL_LATEST_MAJOR
              value: "false"
            - name: NC_DOMAIN
              value: "domain.com"
            - name: NEXTCLOUD_DATA_DIR
              value: /mnt/ncdata
            - name: ONLYOFFICE_ENABLED
              value: "no"
            - name: ONLYOFFICE_HOST
              value: nextcloud-aio-onlyoffice
            - name: ONLYOFFICE_SECRET
              value: ""
            - name: OVERWRITEHOST
              value: "domain.com"
            - name: OVERWRITEPROTOCOL
              value: https
            - name: PHP_MAX_TIME
              value: "3600"
            - name: PHP_MEMORY_LIMIT
              value: "1G"
            - name: PHP_UPLOAD_LIMIT
              value: "10G"
            - name: POSTGRES_DB
              value: nextcloud_database
            - name: POSTGRES_HOST
              value: nextcloud-aio-database
            - name: POSTGRES_PASSWORD
              value: "db_pass"
            - name: POSTGRES_USER
              value: nextcloud
            - name: RECORDING_SECRET
              value: ""
            - name: REDIS_HOST
              value: nextcloud-aio-redis
            - name: REDIS_HOST_PASSWORD
              value: "redis_pass"
            - name: REMOVE_DISABLED_APPS
              value: "true"
            - name: SIGNALING_SECRET
              value: ""
            - name: STARTUP_APPS
              value: "deck twofactor_totp tasks calendar contacts notes"
            - name: TALK_ENABLED
              value: "no"
            - name: TALK_PORT
              value: "3478"
            - name: TALK_RECORDING_ENABLED
              value: "no"
            - name: TALK_RECORDING_HOST
              value: nextcloud-aio-talk-recording
            - name: TRUSTED_CACERTS_DIR
              value: ""
            - name: TURN_SECRET
              value: ""
            - name: TZ
              value: "Asia/Jakarta"
            - name: UPDATE_NEXTCLOUD_APPS
              value: "false"
          image: nextcloud/aio-nextcloud:20231130_081302-latest
          name: nextcloud-aio-nextcloud
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-aio-nextcloud
            - mountPath: /mnt/ncdata
              name: nextcloud-aio-nextcloud-data
            - mountPath: /usr/local/share/ca-certificates
              name: nextcloud-aio-nextcloud-trusted-cacerts
              readOnly: true
          resources: {}
      volumes:
        - name: nextcloud-aio-nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud
        - name: nextcloud-aio-nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud-data
        - name: nextcloud-aio-nextcloud-trusted-cacerts
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud-trusted-cacerts
---
# Source: nextcloud-aio-helm-chart/templates/nextcloud-aio-notify-push-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace nextcloud
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: nextcloud-aio-notify-push
  name: nextcloud-aio-notify-push
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-aio-notify-push
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f latest.yml --namespace nextcloud
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/nextcloud-aio: "true"
        io.kompose.service: nextcloud-aio-notify-push
    spec:
      initContainers:
        - name: init-volumes
          image: alpine:3.18.5
          command:
            - chmod
            - "777"
            - /nextcloud-aio-nextcloud
          volumeMounts:
            - name: nextcloud-aio-nextcloud
              mountPath: /nextcloud-aio-nextcloud
      containers:
        - env:
            - name: NC_DOMAIN
              value: "domain.com"
            - name: NEXTCLOUD_HOST
              value: nextcloud-aio-nextcloud
            - name: POSTGRES_DB
              value: nextcloud_database
            - name: POSTGRES_HOST
              value: nextcloud-aio-database
            - name: POSTGRES_PASSWORD
              value: "db_pass"
            - name: POSTGRES_USER
              value: nextcloud
            - name: REDIS_HOST
              value: nextcloud-aio-redis
            - name: REDIS_HOST_PASSWORD
              value: "redis_pass"
          image: nextcloud/aio-notify-push:20231130_081302-latest
          name: nextcloud-aio-notify-push
          ports:
            - containerPort: 7867
              protocol: TCP
          volumeMounts:
            - mountPath: /nextcloud
              name: nextcloud-aio-nextcloud
              readOnly: true
          resources: {}
      volumes:
        - name: nextcloud-aio-nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-aio-nextcloud