nextcloud:
  host: nextcloud.domain.com
  username: admin
  password: changeme
  extraEnv:
    - name: REDIS_HOST
      value: db.domain.com
    - name: REDIS_HOST_PORT
      value: "6379"
    - name: REDIS_HOST_PASSWORD
      value: pass
    - name: TRUSTED_PROXIES
      value: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
  configs:
    other.config.php: |-
      <?php
      $CONFIG = array (
        'skeletondirectory' => '',
        'lost_password_link' => 'disabled',
        'has_internet_connection' => false,
        'simpleSignUpLink.shown' => false,
      );

persistence:
  enabled: true

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: db.domain.com:5432
  database: nextcloud
  user: id
  password: pass

phpClientHttpsFix:
  enabled: true

cronjob:
  enabled: true

ingress:
  enabled: true
