nextcloud:
  trustedDomains:
    - nextcloud.domain.com
    - nextcloud.kube
  username: admin
  password: changeme
  extraEnv:
    - name: REDIS_HOST
      value: db.domain.com
    - name: REDIS_HOST_PORT
      value: "6379"
    - name: REDIS_HOST_PASSWORD
      value: pass

persistence:
  enabled: true

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: db.domain.com:5432
  database: nextcloud
  user: id
  password: pass

ingress:
  enabled: true
