apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres.domain.com
    port: 5432
    database: keycloakdb
    usernameSecret:
      name: keycloak-secret
      key: DB_USERNAME
    passwordSecret:
      name: keycloak-secret
      key: DB_PASSWORD
  hostname:
    hostname: keycloak.domain.com
  http:
    tlsSecret: keycloak-tls
  ingress:
    enabled: true
    className: haproxy
    tlsSecret: keycloak-tls
    annotations:
      haproxy.org/server-ssl: "true"
      haproxy.org/check: "false"
  proxy:
    headers: xforwarded
  networkPolicy:
    enabled: true
  truststores:
    my-truststore:
      secret:
        name: private-ca
  # features:
  #   enabled:
  #     - admin-fine-grained-authz
  # additionalOptions:
  #   - name: spi-theme-welcome-theme
  #     value: keycloak.v2
  # unsupported:
  #   podTemplate:
  #     spec:
  #       nodeSelector:
  #         kubernetes.io/hostname: node-name
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak
type: Opaque
data:
  DB_USERNAME: username
  DB_PASSWORD: password
